### ISSUE TITLE
Ticking Related Crash [1.20.1] [Fabric]

### ISSUE THREAD

**Issue by eternalbluepetya** [Anxietie/Farmers-Addons#1]
Originally I thought this was a MCA issue since I'm also playing with that, but after looking through the logs, their dev said this mod was the issue. I just randomly crash when flying around. I've increased my memory incase it's a low memory crash, but that doesn't help. It happens I think when I'm around random villages. Here's my [latest.log](https://github.com/Anxietie/Farmers-Addons/files/15325398/latest.log).

**Comment by Anxietie** [comment]
will look into this

**Comment by Anxietie** [comment]
mfw i forget to check if `entity instanceof PlayerEntity` 💀
this is fixed now
